[tool.poetry]
name = "homepage"
version = "2.2.0"
description = "My homepage project"
authors = ["Anttu Suhonen"]

[tool.poetry.dependencies]
python = "^3.10"
fastapi = "^0.120.2"
uvicorn = { version = "^0.38.0", extras = ["standard"] }
requests = "^2.32"
jinja2 = "^3.1"
gunicorn = "^23"
redis = "^5"
celery = "^5.5"

[build-system]
requires = ["poetry-core>=2.2"]
build-backend = "poetry.core.masonry.api"
